default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: MonkeBlogDB
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: TestMonkeBlogDB
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['DBURI'] %>